name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install packages
      run: sudo apt install -y opam zlib1g-dev pkg-config libgmp-dev z3 device-tree-compiler
    - name: Check out repository code
      uses: actions/checkout@HEAD
      with:
        submodules: true
    - name: Ensure pre-commit checks pass
      run: pip install pre-commit && pre-commit run --all-files --show-diff-on-failure --color=always
    - name: Init opam
      run: opam init --disable-sandboxing -y
    - name: Install sail
      run: opam install -y sail
    - name: Build C Simulators
      run: eval $(opam env) && ARCH=64 make c_emulator/riscv_sim_RV32 && ARCH=32 make c_emulator/riscv_sim_RV32
    - name: Upload ARCH=64 model
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: riscv_sim_RV64
        path: c_emulator/riscv_sim_RV64
    - name: Upload ARCH=32 model
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: riscv_sim_RV32
        path: c_emulator/riscv_sim_RV32
    - name: Release ARCH=64 model
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: c_emulator/riscv_sim_RV64
        asset_name: riscv_sim_RV64
