name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
      notes:
        description: 'Release notes'
        required: false


jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            container: rockylinux:8.9.20231119
          # TODO: Mac. We need a Mac binary release of the Sail compiler first.
          # - os: macos-latest
          #   container: ""

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
    # This must be before checkout otherwise Github will use a zip of the
    # code instead of git clone.
    - name: Install dependencies (Linux)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        dnf update -y --enablerepo=devel
        dnf install -y --enablerepo=devel \
            pkg-config \
            gmp-static \
            zlib-static \
            curl \
            git \
            make \
            gcc \
            gcc-c++ \
            cmake \
            ninja-build
        curl --location --output sail.tar.gz https://github.com/rems-project/sail/releases/download/0.18-linux-binary/sail.tar.gz
        tar --directory=/usr/local --strip-components=1 --extract --file sail.tar.gz

    # TODO: Mac
    # - name: Install dependencies (Mac)
    #   if: startsWith(matrix.os, 'macos')
    #   run: |
    #     brew install --force --overwrite ...

    - uses: actions/checkout@v4

    - name: Build simulators
      run: |
        cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Release -DSTATIC=TRUE
        ninja -C build all generated_docs_rv64d

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: |
          build/c_emulator/riscv_sim_rv*
          build/model/riscv_model_rv64d.json
        if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/c_emulator/riscv_sim_rv*
          build/model/riscv_model_rv64d.json
        fail_on_unmatched_files: true
        tag_name: ${{ github.event.inputs.version }}
        body: ${{ github.event.inputs.notes }}
        draft: false
        prerelease: false
